### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ChrisEdson** [mixmaxhq/mongo-aws-xray#2]
Hey there! Any chance you could explain how to use this?

I imagine it's something like:
```es6
const mongoAWSXRay = require('mongo-aws-xray');
AWSXRay.config([mongoAWSXRay.captureMongo()]);
```

Thanks!

**Comment by ttacon** [comment]
Hi! When we wrote this, we were actually using it slightly differently - I've added an example to the [readme](https://github.com/mixmaxhq/mongo-aws-xray#usage). Let me know if that helps!

**Comment by ChrisEdson** [comment]
Thanks very much, that's really helpful. We actually use Mongoose (i.e. a MongoDB ORM), so I think this might be a bit trickier.

But appreciate the readme :)

**Comment by ttacon** [comment]
No problem! We don't actually use XRay anymore 😄. Let me know if you have any questions, though!
